# To enable: uncomment the push and workflow_run triggers below
name: Deploy Dev Environment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - terraform/dev/**
  #     - terraform/modules/**
  # workflow_run:
  #   workflows: [Publish]
  #   types: [completed]
  #   branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run == null}}
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      image_tag: latest
